### ISSUE TITLE
dmg printer gui

### ISSUE THREAD

**Issue by JIGASHI** [MathiasLui/CSGO-Projects#30]
This is currently broken or unfinished? Nothing happens if you try to launch it.

**Comment by MathiasLui** [comment]
I don't use it currently, but it is supposed to work (on csgo, not cs2), and you need 64 bit Windows for it. 

I would have to try it out, the next days, maybe you can see in the Application log of the event viewer if the app crashed with a specific reason? I wouldn't be surprised if I overlooked something since I just wrote it down hastily.

**Comment by MathiasLui** [comment]
I looked into it.

Steam changed how they store the game libraries and it didn't find the CS:GO installation path.

I updated it to .NET 7.0 and included the updated SteamShared module to hopefully fix it.
Build can be downloaded [here](https://gamebanana.com/tools/9444) => Use "sc" version if unsure
